kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: deployrg.azurecr.io/nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 250m
        memory: 256Mi
    volumeMounts:
    - mountPath: "/aks"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azurefile